using System;
using System.Collections.Generic;

namespace LightMemoryDatabase.Util
{
    internal class AutoGeneratedDictionary<TKey, TValue>
    {
        private readonly Func<TKey, TValue> _factory;
        private readonly Dictionary<TKey, TValue> _dictionary;

        public TValue this[TKey key]
        {
            get
            {
                if (!_dictionary.ContainsKey(key))
                    _dictionary.Add(key, _factory(key));

                return _dictionary[key];
            }
        }

        public AutoGeneratedDictionary(Func<TKey, TValue> factory)
        {
            _factory = factory;
            _dictionary = new Dictionary<TKey, TValue>();
        }
    }
}